# Generated by Django 2.1 on 2025-03-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('tutor', models.TextField(max_length=255)),
                ('rate', models.FloatField()),
                ('image', models.FileField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
